package com.mygame.tactics;

import com.badlogic.gdx.utils.Array;

/**
 * Message sent from the server to both clients after processing an action.
 *
 * The server sends one NetworkMessage per processed NetworkAction.
 * CombatScreen reads the events list to drive animations and popups,
 * and reads the gameState snapshot to re-render the board.
 *
 * Two delivery modes are supported:
 *
 *   FULL_STATE  — gameState is a complete snapshot of the current GameState.
 *                 Simpler to implement and more robust (clients can never
 *                 desync), but larger payload. Recommended to start with.
 *
 *   EVENTS_ONLY — gameState is null; clients apply the EngineEvents to their
 *                 local state themselves. Smaller payload but requires clients
 *                 to run GameEngine locally in lockstep. Use later as an
 *                 optimisation once full-state sync is working correctly.
 *
 * Error handling:
 *   If the server rejected the action (wrong team, invalid move, etc.),
 *   success will be false and rejectionReason will explain why.
 *   The client should display rejectionReason and not mutate local state.
 */
public class NetworkMessage {

    public enum Type {
        /** Server processed the action successfully — read gameState and events. */
        ACTION_RESULT,

        /** Server is confirming the client joined a game room successfully. */
        ROOM_JOINED,

        /** The other player disconnected — game is paused or abandoned. */
        OPPONENT_DISCONNECTED,

        /** Server rejected the action — read rejectionReason. */
        ACTION_REJECTED,
        
        DRAFT_UPDATE,
        
        DRAFT_COMPLETE,

        /** Game is over — read gameState.winnerTeam for the result. */
        GAME_OVER,

        /** Ranked: a round just ended. Read round/score fields; next draft is starting. */
        RANKED_ROUND_OVER,

        /** Ranked: all 3 rounds done. Read team1RoundWins/team2RoundWins for final score. */
        RANKED_MATCH_OVER,

        // ---- Lobby / world messages ----

        /** Server → joining client: snapshot of all players currently in the lobby. */
        WORLD_STATE,

        /** Server → all other lobby clients: a new player entered the lobby. */
        PLAYER_JOINED,

        /** Server → all other lobby clients: a player moved to a new tile. */
        PLAYER_MOVED,

        /** Server → all lobby clients: a player left (disconnected or entered a match). */
        PLAYER_LEFT
    }

    /** What kind of message this is. */
    public Type type;

    /** Identifies which game session this message belongs to. */
    public String gameId;

    /**
     * Full snapshot of the current GameState after the action was applied.
     * Null if type is ACTION_REJECTED or OPPONENT_DISCONNECTED.
     */
    public GameState gameState;
    
    public int pickingTeam;
    
    public Array<String> remainingPool = new Array<>();
    
    /**
     * Character names already picked by Team 1.
     * Set on DRAFT_UPDATE and DRAFT_COMPLETE messages.
     */
    public Array<String> team1Picks = new Array<>();
 
    /**
     * Character names already picked by Team 2.
     * Set on DRAFT_UPDATE and DRAFT_COMPLETE messages.
     */
    public Array<String> team2Picks = new Array<>();

    /**
     * Events generated by processing the action.
     * CombatScreen consumes these to spawn popups and trigger animations.
     * Empty if type is not ACTION_RESULT.
     */
    public Array<EngineEvent> events = new Array<>();

    /**
     * True if the server successfully processed the action.
     * False if the action was rejected (see rejectionReason).
     */
    public boolean success;

    /**
     * Human-readable reason the action was rejected.
     * Only set when success is false.
     */
    public String rejectionReason;

    /**
     * Which team number (1 or 2) the receiving client is playing as.
     * Set once on ROOM_JOINED and can be cached by the client.
     */
    public int assignedTeam;

    // ---- Lobby fields ----

    /** PLAYER_JOINED, PLAYER_MOVED, PLAYER_LEFT: the player this message is about. */
    public String lobbyUsername;

    /** PLAYER_JOINED, PLAYER_MOVED: tile coordinates of the player. */
    public int lobbyX, lobbyY;

    /** PLAYER_JOINED: appearance indices for the joining player. */
    public int lobbyModelType    = 0;
    public int lobbySkinColorIdx = 0;
    public int lobbyShirtColorIdx = 0;
    public int lobbyPantsColorIdx = 0;

    /** WORLD_STATE: usernames of all players currently in the lobby. */
    public String[] lobbyUsernames;

    /** WORLD_STATE: tile X/Y positions matching lobbyUsernames. */
    public int[] lobbyXArr;
    public int[] lobbyYArr;

    /** WORLD_STATE: appearance indices matching lobbyUsernames. */
    public int[] lobbyModelTypes;
    public int[] lobbySkinIdxArr;
    public int[] lobbyShirtIdxArr;
    public int[] lobbyPantsIdxArr;

    /** True when this room is a ranked match (3-round format). */
    public boolean isRanked = false;

    /** Current round number (1–3) in a ranked match. */
    public int roundNumber = 0;

    /** Team that won the round that just ended. Set on RANKED_ROUND_OVER. */
    public int roundWinner = 0;

    /** Cumulative round wins for each team. Set on RANKED_ROUND_OVER / RANKED_MATCH_OVER. */
    public int team1RoundWins = 0;
    public int team2RoundWins = 0;

    /** No-arg constructor required for Kryo serialization. */
    public NetworkMessage() {}

    // -----------------------------------------------------------------------
    // Static factory helpers — keeps construction sites readable
    // -----------------------------------------------------------------------

    public static NetworkMessage actionResult(String gameId, GameState state,
                                               Array<EngineEvent> events) {
        NetworkMessage m = new NetworkMessage();
        m.type      = Type.ACTION_RESULT;
        m.gameId    = gameId;
        m.gameState = state;
        m.events    = events;
        m.success   = true;
        return m;
    }

    public static NetworkMessage rejected(String gameId, String reason) {
        NetworkMessage m = new NetworkMessage();
        m.type            = Type.ACTION_REJECTED;
        m.gameId          = gameId;
        m.success         = false;
        m.rejectionReason = reason;
        return m;
    }

    public static NetworkMessage roomJoined(String gameId, int assignedTeam, boolean isRanked) {
        NetworkMessage m = new NetworkMessage();
        m.type         = Type.ROOM_JOINED;
        m.gameId       = gameId;
        m.assignedTeam = assignedTeam;
        m.isRanked     = isRanked;
        m.success      = true;
        return m;
    }

    public static NetworkMessage rankedRoundOver(String gameId, int roundNumber,
            int roundWinner, int team1RoundWins, int team2RoundWins,
            Array<String> nextRoundPool) {
        NetworkMessage m = new NetworkMessage();
        m.type           = Type.RANKED_ROUND_OVER;
        m.gameId         = gameId;
        m.roundNumber    = roundNumber;
        m.roundWinner    = roundWinner;
        m.team1RoundWins = team1RoundWins;
        m.team2RoundWins = team2RoundWins;
        m.remainingPool  = nextRoundPool != null ? nextRoundPool : new Array<>();
        m.success        = true;
        return m;
    }

    public static NetworkMessage rankedMatchOver(String gameId,
            int team1RoundWins, int team2RoundWins) {
        NetworkMessage m = new NetworkMessage();
        m.type           = Type.RANKED_MATCH_OVER;
        m.gameId         = gameId;
        m.team1RoundWins = team1RoundWins;
        m.team2RoundWins = team2RoundWins;
        m.roundWinner    = (team1RoundWins > team2RoundWins) ? 1 : 2;
        m.success        = true;
        return m;
    }

    public static NetworkMessage opponentDisconnected(String gameId) {
        NetworkMessage m = new NetworkMessage();
        m.type    = Type.OPPONENT_DISCONNECTED;
        m.gameId  = gameId;
        m.success = false;
        return m;
    }

    public static NetworkMessage gameOver(String gameId, GameState state) {
        NetworkMessage m = new NetworkMessage();
        m.type      = Type.GAME_OVER;
        m.gameId    = gameId;
        m.gameState = state;
        m.success   = true;
        return m;
    }
    
    public static NetworkMessage draftUpdate(String gameId, int pickingTeam,
            Array<String> pool,
            Array<String> t1, Array<String> t2) {
        NetworkMessage m = new NetworkMessage();
        m.type          = Type.DRAFT_UPDATE;
        m.gameId        = gameId;
        m.success       = true;
        m.pickingTeam   = pickingTeam;
        m.remainingPool = pool;
        m.team1Picks    = t1;
        m.team2Picks    = t2;
        return m;
    }

    public static NetworkMessage draftComplete(String gameId,
            Array<String> t1, Array<String> t2) {
        NetworkMessage m = new NetworkMessage();
        m.type       = Type.DRAFT_COMPLETE;
        m.gameId     = gameId;
        m.success    = true;
        m.team1Picks = t1;
        m.team2Picks = t2;
        return m;
    }

    public static NetworkMessage worldState(String[] usernames, int[] xs, int[] ys,
            int[] modelTypes, int[] skinIdxs, int[] shirtIdxs, int[] pantsIdxs) {
        NetworkMessage m = new NetworkMessage();
        m.type              = Type.WORLD_STATE;
        m.success           = true;
        m.lobbyUsernames    = usernames;
        m.lobbyXArr         = xs;
        m.lobbyYArr         = ys;
        m.lobbyModelTypes   = modelTypes;
        m.lobbySkinIdxArr   = skinIdxs;
        m.lobbyShirtIdxArr  = shirtIdxs;
        m.lobbyPantsIdxArr  = pantsIdxs;
        return m;
    }

    public static NetworkMessage playerJoined(String username, int x, int y,
            int modelType, int skinColorIdx, int shirtColorIdx, int pantsColorIdx) {
        NetworkMessage m = new NetworkMessage();
        m.type               = Type.PLAYER_JOINED;
        m.success            = true;
        m.lobbyUsername      = username;
        m.lobbyX             = x;
        m.lobbyY             = y;
        m.lobbyModelType     = modelType;
        m.lobbySkinColorIdx  = skinColorIdx;
        m.lobbyShirtColorIdx = shirtColorIdx;
        m.lobbyPantsColorIdx = pantsColorIdx;
        return m;
    }

    public static NetworkMessage playerMoved(String username, int x, int y) {
        NetworkMessage m = new NetworkMessage();
        m.type          = Type.PLAYER_MOVED;
        m.success       = true;
        m.lobbyUsername = username;
        m.lobbyX        = x;
        m.lobbyY        = y;
        return m;
    }

    public static NetworkMessage playerLeft(String username) {
        NetworkMessage m = new NetworkMessage();
        m.type          = Type.PLAYER_LEFT;
        m.success       = true;
        m.lobbyUsername = username;
        return m;
    }
}